const devices = {
  BodyModule: 0x00,
  SunroofControl: 0x08,
  CDChanger: 0x18,
  RadioControlledClock: 0x28,
  CheckControlModule: 0x30,
  GraphicsNavigationDriver: 0x3b,
  Diagnostic: 0x3f,
  RemoteControlCentralLocking: 0x40,
  GraphicsDriverRearScreen: 0x43,
  Immobiliser: 0x44,
  CentralInformationDisplay: 0x46,
  MultiFunctionSteeringWheel: 0x50,
  MirrorMemory: 0x51,
  IntegratedHeatingAndAirConditioning: 0x5b,
  ParkDistanceControl: 0x60,
  Radio: 0x68,
  DigitalSignalProcessingAudioAmplifier: 0x6a,
  SeatMemory: 0x72,
  SiriusRadio: 0x73,
  CDChangerDINsize: 0x76,
  NavigationEurope: 0x7f,
  InstrumentClusterElectronics: 0x80,
  MirrorMemorySecond: 0x9b,
  MirrorMemoryThird: 0x9c,
  RearMultiInfoDisplay: 0xa0,
  AirBagModule: 0xa4,
  SpeedRecognitionSystem: 0xb0,
  NavigationJapan: 0xbb,
  GlobalBroadcastAddress: 0xbf,
  MultiInfoDisplay: 0xc0,
  Telephone: 0xc8,
  Assist: 0xca,
  LightControlModule: 0xd0,
  SeatMemorySecond: 0xda,
  IntegratedRadioInformationSystem: 0xe0,
  FrontDisplay: 0xe7,
  RainLightSensor: 0xe8,
  Television: 0xed,
  OnBoardMonitor: 0xf0,
  Broadcast: 0xff,
};

export { devices };
